### ISSUE TITLE
PCB Lib Molex KK 254 Angles 01x10 and 01x12 request

### ISSUE THREAD

**Issue by daweed38** [SnowMB/pcb_library#1]
Hello,

Could you please add 01x10 and 01x12 Molex KK 254 Horizontal footprint and 3d package please

Regards

Daweed

**Comment by SnowMB** [comment]
The 3d packages were done by a friend of mine, and I'm not sure if he still has the sources to build the new variants, but I can quickly do the footprints for you.

**Comment by daweed38** [comment]
Thank you very much.
Best regards

Daweed
