### ISSUE TITLE
in 3d models, tabs are inverted

### ISSUE THREAD

**Issue by hb020** [SnowMB/pcb_library#3]
when looking at the [molex 3d model](https://www.molex.com/molex/products/datasheet.jsp?part=active/0022053081_PCB_HEADERS.xml), the tabs are on the opposite side of your model. The model that can be downloaded from molex is to scale, but rotated and shifted, so would need some tweaking.

**Comment by SnowMB** [comment]
Yeah, I know that this model does not match the official model. However I designed this for connectors I had laying around that i did not know the part number of. The closest one was this and for the footprint it makes no difference.
